### ISSUE TITLE
"Deus in adiutorium" as two versicles

### ISSUE THREAD

**Issue by igneus** [monicalabbao/brevarium-romanum-api#4]
I noticed that you structure *Deus in adiutorium* as a pair of versicles:

> V: Deus in adiutorium ... R: Domine ad adiuvandum ...
> V: Gloria Patri ... R: Sicut erat ...

https://github.com/monicalabbao/brevarium-romanum-api/blob/75797a40df3ec7d1eef1df466924d9e945c1b2e6/server/models/sunday-hours.js#L9

I guess it might be inspired by divinumofficium.com, but in this respect the venerable online breviary is just wrong. It's true that "Deus in adiutorium" is quite often performed this way, especially in non-monastic contexts, but in breviaries it's always laid out another way:

> V: Deus in adiutorium ... R: Domine ad adiuvandum ... _[all the way down to]_ Amen. Alleluia.

See e. g. https://books.google.cz/books?id=hq1NWL5SxqAC&dq=breviarium%20romanum&pg=PA2-IA35#v=onepage&q&f=false

**Comment by monicavaldez** [comment]
PR made in reference to this issue: https://github.com/monicalabbao/brevarium-romanum-api/pull/10. Like this?

Thank you for reviewing @igneus :D

**Comment by igneus** [comment]
Yes, now it's definitely more like in printed breviaries - except of the asterisks.

**Comment by monicavaldez** [comment]
I removed the asterisks now...

**Comment by monicavaldez** [comment]
Closing issue now, but can be reopened :D
